### ISSUE TITLE
Intégration StrawPoll

### ISSUE THREAD

**Issue by Blood4S** [sucresware/4sucres#147]
_"StrawPoll.me n'autorise pas la connexion"_
![Eiy0Hl2](https://user-images.githubusercontent.com/8051543/88462661-6ce78e00-cead-11ea-9bd2-b6b5cd8d4ad7.png)

**Comment by mgkprod** [comment]
Sûrement une erreur de regex. A voir également, y'a peut être un conflit avec strawpoll.com

https://github.com/4sucres/board/blob/b51c7e605f8a42f4fbd8d5c22dcd9dc6ae3dca1a/app/Helpers/SucresParser.php#L369

**Comment by mgkprod** [comment]
Corrigé ici : https://github.com/sucresware/4sucres/commit/29a8b8764dedb13f1e97dc46529f9d659fedefee
