### ISSUE TITLE
SimpleMDE sur mobile c'est pas fou

### ISSUE THREAD

**Issue by Edou68FR** [sucresware/4sucres#41]
L'autocomplétion lors de l'identification de quelqu'un sur un post ne fonctionne pas sous Android. 
Version Android : Android 8.0
Appareil : Honor 8
Version application chrome : 74.0.3729.136
Voir la capture d'écran jointe.
![Screenshot_20190521-092105](https://user-images.githubusercontent.com/31824624/58084986-29640680-7bbc-11e9-80c6-8dca67768083.jpg)

**Comment by mgkprod** [comment]
Globalement l'éditeur est pété sur mobile. Il faut chercher une alternative 🤔

**Comment by mgkprod** [comment]
J'ai reclassé l'issue.

On peut ajouter que :
- le correcteur ortho des navigateurs ne fonctionne plus dans le champ
- le shift automatique sur mobile ne fonctionne pas
- il est impossible de séléctionner du texte "correctement" sur mobile

**Comment by hawezo** [comment]
Une possible correction temporaire est de ne pas initialiser SimpleMDE si l'utilisateur est sur téléphone. 

Inconvénients : 
- Pas de raccourcis pour les options principales de formatage
- Plus de "pseudo-wysiwyg"

Avantages : 
- Correcteur orthographique de retour 
- Auto-complétion de mentions de retour 
- Les balises faites maison, Imgur, Risibank restent

**Comment by hawezo** [comment]
Solution possible ; utiliser ce fork de `SimpleMDE` : https://github.com/Ionaru/easy-markdown-editor (cc @mgkprod).

Il a notamment un spellcheck et ça règlera le problème des icônes de notification qui se rapprochent quand une instance de `SimpleMDE` est initialisée.

**Comment by mgkprod** [comment]
> Il a notamment un spellcheck
SimpleMDE aussi, mais qu'en anglais
