### ISSUE TITLE
Ajouter l'intégration des liens imgur

### ISSUE THREAD

**Issue by mgkprod** [sucresware/4sucres#57]
Seulement à partir d'un lien genre comme ça : https://imgur.com/JSmDfQV
ça permet d'afficher autre chose que les images classiques (gifv notamment)

**Comment by hawezo** [comment]
Il faut prendre en compte les deux types de liens possibles : 
- https://i.imgur.com/JSmDfQV.gifv
- https://imgur.com/JSmDfQV

**Comment by hawezo** [comment]
Je pense qu'il faut passer par l'API Imgur (https://apidocs.imgur.com/?version=latest#2078c7e0-c2b8-4bc8-a646-6e544b087d0f).

On peut récupérer le hash de l'image avec une expression régulière et faire une requête qui va nous retourner une URL directe (`data.link`) pour pouvoir l'afficher correctement. 

Le problème si on ne fait pas ça, c'est que si l'utilisateur fournit un lien normal (https://imgur.com/JSmDfQV) on ne pourra pas l'afficher correctement car ce lien mène vers une page directe, et on n'a pas l'extension.

**Comment by hawezo** [comment]
Ou alors utiliser https://help.imgur.com/hc/en-us/articles/211273743-Embed-Unit. Tu préfères quelle solution @mgkprod ?

**Comment by hawezo** [comment]
Requiert la résolution de #75

**Comment by mgkprod** [comment]
Implémenté, ticket non mis à jour :(
