### ISSUE TITLE
Alternative à Parsedown

### ISSUE THREAD

**Issue by mgkprod** [sucresware/4sucres#75]
J'ai trouvé ce package qui me parait intéressant : https://github.com/cebe/markdown
- Compatible GFM
- Facilement extensible (à première vue) : https://github.com/cebe/markdown#extending-the-language-

J'ai bien aimé dans la FAQ :

> Why another markdown parser?
> The only implentation that I have found that uses this approach is Parsedown [...]. Parsedown however is an implementation that focuses on speed and implements its own flavor [...] in one class and at the time of this writing was not easily extensible.

Permet de résoudre #42 dans la foulée :
> `$parser->enableNewlines = true` to convert all newlines to `<br/>` tags

Tu veux t'en charger @hawezo  ?

**Comment by hawezo** [comment]
Oui ça m'intéresse, je peux peut-être voir ça ce soir, au pire ce week-end

**Comment by hawezo** [comment]
Je commencerai à m'en occuper une fois que tout sera au propre (notamment https://github.com/4sucres/board/tree/hawezo-master).

**Comment by Youssefayt** [comment]
On code en web et on se sent dév

**Comment by mgkprod** [comment]
Pour autoriser l'HTML et se sécuriser, y'a moyen de passer par un purifier comme celui-ci 👍 
https://kuztek.com/blog/use-laravel-purifier-security

**Comment by mgkprod** [comment]
Plus d'actualité
